#
language: python

env:
  global:
    #- DEPENDS="cython>=0.19"
    - NO_NET=1

git:
    depth: 1000

matrix:
  include:
      - python: 3.5
        dist: trusty
        sudo: false
        before_script:
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"
          - sleep 3 # give xvfb some time to start
      - python: 3.6
        dist: trusty
        sudo: false
        before_script:
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"
      - python: 3.7
        dist: xenial
        sudo: true
        services:
          - xvfb

# start Virtual X, so default matplotlib backend works
before_script:
    - pip install --upgrade pip
    - pip install codecov
    - pip install pytest-cov

# Install dependencies
install:
    - pip install -r requirements.travis.txt
    - pip install -e .

# command to run tests
script:
   - py.test ./tests --cov=pastas --cov-report=xml

after_success:
   - codecov
